language: go
dist: xenial
sudo: true
services: [docker]

matrix:
  include:
  - os: linux
    go: 1.14.x

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: Ai7efi3yilhxCCjCW6QSQrkk0aYF6unjBDdVywotXg1jTzrNnL1KFPR7vK5AHcU9iakhSrvRYY/wYHs9MV/al+FmTEBHD5QB5+V7QdqiOVVCDjbItP3M16ni14q5s2MwfPsgELIAJoKGIgjdJ7Rwbtd04Oqa1GmA4BzVkr+0TIbbRO85ds7jZUUnpQY3T0MGT8sPoLr4K/iBj6M9BLDlT6j9sEWjVscFkNlN5Q9q7M3/QyZvRlASvXg6FaBhDud1Sn0AOAOJLu0Nq4rv3ZK9+PeURovNalFcq20EwHyoan9IacZ73nPWerwov2JMWBCVcdGffmkZ2DlUa/T15kQkrflPn48CSn1hq5jut9yZpNg7a+BTEOSdlzSb78aS10JRjQ5Ke0Y/6xc5bIeKzgWeICpSGkl1A3rQ6DN8ZRL3gIfx4FfaBDoszQcZQFrmMm21g/QdN1m+MxP9U5bEODWdl9PAo27n11UY5ItMymHw5qaGw3HXUbHk7X+qUHjEWtW/z4dQQJMAzfXCWrx92tEavFE9/gvYtybpn1dfw1O2FlxCxSCkk2AejC/E6RMCgGaDV3SvIzYn+ai0ijwn8o4/fKoaKc8vjIpCDXGvWxAfBkhFRkQ38n3fpBhgYp8THD98jU3XNXsN0ltFfCEJQ3KpPGyCUbbvBnsqPvols0HuaX4=
  file_glob: true
  file:
    - bin/customers-*
    - bin/customers.exe
  on:
    repo: moov-io/customers
    tags: true
    go: 1.14.x
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

notifications:
  slack:
    secure: R8172Z70q4SIOQkSRUqC4Q2tSc+Ip+oWx3uyagYnx4cHeIR/uO1sPJlLZH13OVdqsDyoMywlLX31WC94EUPXvAwx+EPTOhGAs49TaY9pmOYlEe4MeWyJilHQMZl7I7geU9shRdW43kyR78+claY1n6FAIWdtzIskcwlOglc2TF+/2hOm5cZJpPmwhsF/8GDBCdUHNGj8uHkx1E4AfraCLOLVvB+1M8gbex8pYWHxOSpbiWbuDMhhJkBiQzlLcWcV0WpepwsukY+3HXsvj1+A2b1zleI6CL0ikKo4qPdNWhJD+iYDUk0bMOHihFEfcqmeGbehCwoWkJDNcAZG3TO4e57HniQE1L0usAqIWq+tK4gt3fWVPU7XqLHFhpN3VHbMxMmry8UQhy8hxN+M38Tgue2tVE3qbyZ1Nlg81IKFMJg/m01NR53NlVzXwWAzE5QR4NccTDkLkau/PER3QDsUSHBbiz69Ie9qCxiRStD4anQ4ZoQrR0d522WGGh6doIj6kKxE88V8SszBNNYebqGxN2yqZb2wpBVmr1zYFEX3bvK1nlSA2vk24MapMSozKKoq94TSx4Sw2Ya0To0z18MS4KXP8uylLckGejZ/2Fw6Pt9T0PUkcEIWmOrdeAwqIf1CVyfa7IVhiXA7QV2dp+qLijCl306ZJUG0uIiaNf452c8=
